2023-10-24 10:40:04,328:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-10-24 10:40:04,328:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-10-24 10:40:04,328:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-10-24 10:40:04,329:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-10-24 10:40:09,021:INFO:PyCaret ClassificationExperiment
2023-10-24 10:40:09,021:INFO:Logging name: clf-default-name
2023-10-24 10:40:09,021:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-10-24 10:40:09,021:INFO:version 3.1.0
2023-10-24 10:40:09,022:INFO:Initializing setup()
2023-10-24 10:40:09,022:INFO:self.USI: f850
2023-10-24 10:40:09,022:INFO:self._variable_keys: {'fold_groups_param', 'logging_param', 'fold_shuffle_param', 'n_jobs_param', '_available_plots', 'pipeline', '_ml_usecase', 'html_param', 'exp_name_log', 'memory', 'idx', 'seed', 'y_test', 'USI', 'fold_generator', 'gpu_param', 'X_train', 'data', 'gpu_n_jobs_param', 'X_test', 'y_train', 'fix_imbalance', 'exp_id', 'target_param', 'log_plots_param', 'y', 'X', 'is_multiclass'}
2023-10-24 10:40:09,022:INFO:Checking environment
2023-10-24 10:40:09,022:INFO:python_version: 3.10.11
2023-10-24 10:40:09,022:INFO:python_build: ('v3.10.11:7d4cc5aa85', 'Apr  4 2023 19:05:19')
2023-10-24 10:40:09,022:INFO:machine: arm64
2023-10-24 10:40:09,022:INFO:platform: macOS-13.2.1-arm64-arm-64bit
2023-10-24 10:40:09,022:INFO:Memory: svmem(total=17179869184, available=5092147200, percent=70.4, used=7524548608, free=52609024, active=5053726720, inactive=4987961344, wired=2470821888)
2023-10-24 10:40:09,022:INFO:Physical Core: 8
2023-10-24 10:40:09,022:INFO:Logical Core: 8
2023-10-24 10:40:09,022:INFO:Checking libraries
2023-10-24 10:40:09,022:INFO:System:
2023-10-24 10:40:09,022:INFO:    python: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
2023-10-24 10:40:09,022:INFO:executable: /Users/charlesnanakwakye/cloud_AI_Group4/venv/bin/python
2023-10-24 10:40:09,022:INFO:   machine: macOS-13.2.1-arm64-arm-64bit
2023-10-24 10:40:09,022:INFO:PyCaret required dependencies:
2023-10-24 10:40:09,285:INFO:                 pip: 23.2.1
2023-10-24 10:40:09,285:INFO:          setuptools: 65.5.0
2023-10-24 10:40:09,285:INFO:             pycaret: 3.1.0
2023-10-24 10:40:09,285:INFO:             IPython: 8.16.1
2023-10-24 10:40:09,285:INFO:          ipywidgets: 8.1.1
2023-10-24 10:40:09,285:INFO:                tqdm: 4.66.1
2023-10-24 10:40:09,285:INFO:               numpy: 1.23.5
2023-10-24 10:40:09,285:INFO:              pandas: 1.5.3
2023-10-24 10:40:09,285:INFO:              jinja2: 3.1.2
2023-10-24 10:40:09,285:INFO:               scipy: 1.10.1
2023-10-24 10:40:09,285:INFO:              joblib: 1.3.2
2023-10-24 10:40:09,285:INFO:             sklearn: 1.2.2
2023-10-24 10:40:09,285:INFO:                pyod: 1.1.0
2023-10-24 10:40:09,285:INFO:            imblearn: 0.11.0
2023-10-24 10:40:09,285:INFO:   category_encoders: 2.6.2
2023-10-24 10:40:09,285:INFO:            lightgbm: 4.1.0
2023-10-24 10:40:09,285:INFO:               numba: 0.58.1
2023-10-24 10:40:09,285:INFO:            requests: 2.31.0
2023-10-24 10:40:09,285:INFO:          matplotlib: 3.8.0
2023-10-24 10:40:09,286:INFO:          scikitplot: 0.3.7
2023-10-24 10:40:09,286:INFO:         yellowbrick: 1.5
2023-10-24 10:40:09,286:INFO:              plotly: 5.17.0
2023-10-24 10:40:09,286:INFO:    plotly-resampler: Not installed
2023-10-24 10:40:09,286:INFO:             kaleido: 0.2.1
2023-10-24 10:40:09,286:INFO:           schemdraw: 0.15
2023-10-24 10:40:09,286:INFO:         statsmodels: 0.14.0
2023-10-24 10:40:09,286:INFO:              sktime: 0.21.1
2023-10-24 10:40:09,286:INFO:               tbats: 1.1.3
2023-10-24 10:40:09,286:INFO:            pmdarima: 2.0.4
2023-10-24 10:40:09,286:INFO:              psutil: 5.9.5
2023-10-24 10:40:09,286:INFO:          markupsafe: 2.1.3
2023-10-24 10:40:09,286:INFO:             pickle5: Not installed
2023-10-24 10:40:09,286:INFO:         cloudpickle: 3.0.0
2023-10-24 10:40:09,286:INFO:         deprecation: 2.1.0
2023-10-24 10:40:09,286:INFO:              xxhash: 3.4.1
2023-10-24 10:40:09,286:INFO:           wurlitzer: 3.0.3
2023-10-24 10:40:09,286:INFO:PyCaret optional dependencies:
2023-10-24 10:40:09,294:INFO:                shap: Not installed
2023-10-24 10:40:09,294:INFO:           interpret: Not installed
2023-10-24 10:40:09,294:INFO:                umap: Not installed
2023-10-24 10:40:09,294:INFO:     ydata_profiling: Not installed
2023-10-24 10:40:09,294:INFO:  explainerdashboard: Not installed
2023-10-24 10:40:09,294:INFO:             autoviz: Not installed
2023-10-24 10:40:09,294:INFO:           fairlearn: Not installed
2023-10-24 10:40:09,294:INFO:          deepchecks: Not installed
2023-10-24 10:40:09,294:INFO:             xgboost: Not installed
2023-10-24 10:40:09,294:INFO:            catboost: Not installed
2023-10-24 10:40:09,294:INFO:              kmodes: Not installed
2023-10-24 10:40:09,295:INFO:             mlxtend: Not installed
2023-10-24 10:40:09,295:INFO:       statsforecast: Not installed
2023-10-24 10:40:09,295:INFO:        tune_sklearn: Not installed
2023-10-24 10:40:09,295:INFO:                 ray: Not installed
2023-10-24 10:40:09,295:INFO:            hyperopt: Not installed
2023-10-24 10:40:09,295:INFO:              optuna: Not installed
2023-10-24 10:40:09,295:INFO:               skopt: Not installed
2023-10-24 10:40:09,295:INFO:              mlflow: Not installed
2023-10-24 10:40:09,295:INFO:              gradio: Not installed
2023-10-24 10:40:09,295:INFO:             fastapi: Not installed
2023-10-24 10:40:09,295:INFO:             uvicorn: Not installed
2023-10-24 10:40:09,295:INFO:              m2cgen: Not installed
2023-10-24 10:40:09,295:INFO:           evidently: Not installed
2023-10-24 10:40:09,295:INFO:               fugue: Not installed
2023-10-24 10:40:09,295:INFO:           streamlit: Not installed
2023-10-24 10:40:09,295:INFO:             prophet: Not installed
2023-10-24 10:40:09,295:INFO:None
2023-10-24 10:40:09,295:INFO:Set up data.
2023-10-24 10:40:09,298:INFO:Set up folding strategy.
2023-10-24 10:40:09,298:INFO:Set up train/test split.
2023-10-24 10:40:09,301:INFO:Set up index.
2023-10-24 10:40:09,301:INFO:Assigning column types.
2023-10-24 10:40:09,302:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-10-24 10:40:09,332:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-10-24 10:40:09,338:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-10-24 10:40:09,377:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,377:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,406:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-10-24 10:40:09,407:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-10-24 10:40:09,425:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,425:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,425:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-10-24 10:40:09,455:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-10-24 10:40:09,473:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,473:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,503:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-10-24 10:40:09,520:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,521:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,521:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-10-24 10:40:09,570:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,570:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,618:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,618:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,619:INFO:Preparing preprocessing pipeline...
2023-10-24 10:40:09,620:INFO:Set up simple imputation.
2023-10-24 10:40:09,631:INFO:Finished creating preprocessing pipeline.
2023-10-24 10:40:09,636:INFO:Pipeline: Pipeline(memory=FastMemory(location=/var/folders/h8/ybzdwy6x03l4xpqzfc0k7kpr0000gn/T/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['pclass', 'sex', 'age', 'sibsp',
                                             'parch', 'fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False)
2023-10-24 10:40:09,636:INFO:Creating final display dataframe.
2023-10-24 10:40:09,669:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target          survived
2                   Target type            Binary
3           Original data shape         (1045, 7)
4        Transformed data shape         (1045, 7)
5   Transformed train set shape          (731, 7)
6    Transformed test set shape          (314, 7)
7              Numeric features                 6
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              f850
2023-10-24 10:40:09,722:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,722:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,770:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,770:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-10-24 10:40:09,770:INFO:setup() successfully completed in 0.75s...............
2023-10-24 10:40:09,775:INFO:Initializing compare_models()
2023-10-24 10:40:09,776:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-10-24 10:40:09,776:INFO:Checking exceptions
2023-10-24 10:40:09,778:INFO:Preparing display monitor
2023-10-24 10:40:09,833:INFO:Initializing Logistic Regression
2023-10-24 10:40:09,833:INFO:Total runtime is 5.7140986124674475e-06 minutes
2023-10-24 10:40:09,836:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:09,837:INFO:Initializing create_model()
2023-10-24 10:40:09,837:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:09,837:INFO:Checking exceptions
2023-10-24 10:40:09,837:INFO:Importing libraries
2023-10-24 10:40:09,837:INFO:Copying training dataset
2023-10-24 10:40:09,840:INFO:Defining folds
2023-10-24 10:40:09,840:INFO:Declaring metric variables
2023-10-24 10:40:09,843:INFO:Importing untrained model
2023-10-24 10:40:09,846:INFO:Logistic Regression Imported successfully
2023-10-24 10:40:09,851:INFO:Starting cross validation
2023-10-24 10:40:09,852:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:13,638:INFO:Calculating mean and std
2023-10-24 10:40:13,644:INFO:Creating metrics dataframe
2023-10-24 10:40:13,657:INFO:Uploading results into container
2023-10-24 10:40:13,658:INFO:Uploading model into container now
2023-10-24 10:40:13,659:INFO:_master_model_container: 1
2023-10-24 10:40:13,659:INFO:_display_container: 2
2023-10-24 10:40:13,661:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-10-24 10:40:13,661:INFO:create_model() successfully completed......................................
2023-10-24 10:40:13,762:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:13,762:INFO:Creating metrics dataframe
2023-10-24 10:40:13,769:INFO:Initializing K Neighbors Classifier
2023-10-24 10:40:13,770:INFO:Total runtime is 0.06560833056767781 minutes
2023-10-24 10:40:13,772:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:13,772:INFO:Initializing create_model()
2023-10-24 10:40:13,772:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:13,772:INFO:Checking exceptions
2023-10-24 10:40:13,772:INFO:Importing libraries
2023-10-24 10:40:13,773:INFO:Copying training dataset
2023-10-24 10:40:13,776:INFO:Defining folds
2023-10-24 10:40:13,776:INFO:Declaring metric variables
2023-10-24 10:40:13,779:INFO:Importing untrained model
2023-10-24 10:40:13,782:INFO:K Neighbors Classifier Imported successfully
2023-10-24 10:40:13,787:INFO:Starting cross validation
2023-10-24 10:40:13,788:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:13,911:INFO:Calculating mean and std
2023-10-24 10:40:13,912:INFO:Creating metrics dataframe
2023-10-24 10:40:13,914:INFO:Uploading results into container
2023-10-24 10:40:13,915:INFO:Uploading model into container now
2023-10-24 10:40:13,915:INFO:_master_model_container: 2
2023-10-24 10:40:13,915:INFO:_display_container: 2
2023-10-24 10:40:13,915:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-10-24 10:40:13,916:INFO:create_model() successfully completed......................................
2023-10-24 10:40:13,982:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:13,982:INFO:Creating metrics dataframe
2023-10-24 10:40:13,989:INFO:Initializing Naive Bayes
2023-10-24 10:40:13,989:INFO:Total runtime is 0.06926089525222778 minutes
2023-10-24 10:40:13,991:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:13,991:INFO:Initializing create_model()
2023-10-24 10:40:13,991:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:13,992:INFO:Checking exceptions
2023-10-24 10:40:13,992:INFO:Importing libraries
2023-10-24 10:40:13,992:INFO:Copying training dataset
2023-10-24 10:40:13,994:INFO:Defining folds
2023-10-24 10:40:13,994:INFO:Declaring metric variables
2023-10-24 10:40:13,996:INFO:Importing untrained model
2023-10-24 10:40:13,998:INFO:Naive Bayes Imported successfully
2023-10-24 10:40:14,002:INFO:Starting cross validation
2023-10-24 10:40:14,003:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:14,086:INFO:Calculating mean and std
2023-10-24 10:40:14,087:INFO:Creating metrics dataframe
2023-10-24 10:40:14,091:INFO:Uploading results into container
2023-10-24 10:40:14,091:INFO:Uploading model into container now
2023-10-24 10:40:14,092:INFO:_master_model_container: 3
2023-10-24 10:40:14,092:INFO:_display_container: 2
2023-10-24 10:40:14,092:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-10-24 10:40:14,092:INFO:create_model() successfully completed......................................
2023-10-24 10:40:14,159:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:14,159:INFO:Creating metrics dataframe
2023-10-24 10:40:14,166:INFO:Initializing Decision Tree Classifier
2023-10-24 10:40:14,166:INFO:Total runtime is 0.07222237984339396 minutes
2023-10-24 10:40:14,169:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:14,169:INFO:Initializing create_model()
2023-10-24 10:40:14,169:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:14,169:INFO:Checking exceptions
2023-10-24 10:40:14,170:INFO:Importing libraries
2023-10-24 10:40:14,170:INFO:Copying training dataset
2023-10-24 10:40:14,172:INFO:Defining folds
2023-10-24 10:40:14,172:INFO:Declaring metric variables
2023-10-24 10:40:14,174:INFO:Importing untrained model
2023-10-24 10:40:14,176:INFO:Decision Tree Classifier Imported successfully
2023-10-24 10:40:14,180:INFO:Starting cross validation
2023-10-24 10:40:14,181:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:14,246:INFO:Calculating mean and std
2023-10-24 10:40:14,246:INFO:Creating metrics dataframe
2023-10-24 10:40:14,249:INFO:Uploading results into container
2023-10-24 10:40:14,249:INFO:Uploading model into container now
2023-10-24 10:40:14,250:INFO:_master_model_container: 4
2023-10-24 10:40:14,250:INFO:_display_container: 2
2023-10-24 10:40:14,250:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-10-24 10:40:14,250:INFO:create_model() successfully completed......................................
2023-10-24 10:40:14,317:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:14,317:INFO:Creating metrics dataframe
2023-10-24 10:40:14,323:INFO:Initializing SVM - Linear Kernel
2023-10-24 10:40:14,323:INFO:Total runtime is 0.0748395005861918 minutes
2023-10-24 10:40:14,325:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:14,326:INFO:Initializing create_model()
2023-10-24 10:40:14,326:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:14,326:INFO:Checking exceptions
2023-10-24 10:40:14,326:INFO:Importing libraries
2023-10-24 10:40:14,326:INFO:Copying training dataset
2023-10-24 10:40:14,328:INFO:Defining folds
2023-10-24 10:40:14,328:INFO:Declaring metric variables
2023-10-24 10:40:14,330:INFO:Importing untrained model
2023-10-24 10:40:14,332:INFO:SVM - Linear Kernel Imported successfully
2023-10-24 10:40:14,337:INFO:Starting cross validation
2023-10-24 10:40:14,337:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:14,358:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,361:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,362:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,365:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,367:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,371:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,375:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,378:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,381:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,383:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-10-24 10:40:14,387:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:14,393:INFO:Calculating mean and std
2023-10-24 10:40:14,394:INFO:Creating metrics dataframe
2023-10-24 10:40:14,397:INFO:Uploading results into container
2023-10-24 10:40:14,397:INFO:Uploading model into container now
2023-10-24 10:40:14,398:INFO:_master_model_container: 5
2023-10-24 10:40:14,398:INFO:_display_container: 2
2023-10-24 10:40:14,398:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-10-24 10:40:14,398:INFO:create_model() successfully completed......................................
2023-10-24 10:40:14,463:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:14,463:INFO:Creating metrics dataframe
2023-10-24 10:40:14,470:INFO:Initializing Ridge Classifier
2023-10-24 10:40:14,470:INFO:Total runtime is 0.07728463013966877 minutes
2023-10-24 10:40:14,472:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:14,472:INFO:Initializing create_model()
2023-10-24 10:40:14,473:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:14,473:INFO:Checking exceptions
2023-10-24 10:40:14,473:INFO:Importing libraries
2023-10-24 10:40:14,473:INFO:Copying training dataset
2023-10-24 10:40:14,475:INFO:Defining folds
2023-10-24 10:40:14,475:INFO:Declaring metric variables
2023-10-24 10:40:14,477:INFO:Importing untrained model
2023-10-24 10:40:14,479:INFO:Ridge Classifier Imported successfully
2023-10-24 10:40:14,483:INFO:Starting cross validation
2023-10-24 10:40:14,484:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:14,501:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,504:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,505:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,508:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,512:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,515:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,516:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,517:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,520:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,523:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-10-24 10:40:14,529:INFO:Calculating mean and std
2023-10-24 10:40:14,530:INFO:Creating metrics dataframe
2023-10-24 10:40:14,532:INFO:Uploading results into container
2023-10-24 10:40:14,532:INFO:Uploading model into container now
2023-10-24 10:40:14,533:INFO:_master_model_container: 6
2023-10-24 10:40:14,533:INFO:_display_container: 2
2023-10-24 10:40:14,533:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-10-24 10:40:14,533:INFO:create_model() successfully completed......................................
2023-10-24 10:40:14,597:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:14,597:INFO:Creating metrics dataframe
2023-10-24 10:40:14,604:INFO:Initializing Random Forest Classifier
2023-10-24 10:40:14,604:INFO:Total runtime is 0.0795209487279256 minutes
2023-10-24 10:40:14,606:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:14,607:INFO:Initializing create_model()
2023-10-24 10:40:14,607:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:14,607:INFO:Checking exceptions
2023-10-24 10:40:14,607:INFO:Importing libraries
2023-10-24 10:40:14,607:INFO:Copying training dataset
2023-10-24 10:40:14,609:INFO:Defining folds
2023-10-24 10:40:14,609:INFO:Declaring metric variables
2023-10-24 10:40:14,611:INFO:Importing untrained model
2023-10-24 10:40:14,613:INFO:Random Forest Classifier Imported successfully
2023-10-24 10:40:14,617:INFO:Starting cross validation
2023-10-24 10:40:14,619:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:15,335:INFO:Calculating mean and std
2023-10-24 10:40:15,336:INFO:Creating metrics dataframe
2023-10-24 10:40:15,339:INFO:Uploading results into container
2023-10-24 10:40:15,339:INFO:Uploading model into container now
2023-10-24 10:40:15,339:INFO:_master_model_container: 7
2023-10-24 10:40:15,339:INFO:_display_container: 2
2023-10-24 10:40:15,340:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-10-24 10:40:15,340:INFO:create_model() successfully completed......................................
2023-10-24 10:40:15,412:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:15,412:INFO:Creating metrics dataframe
2023-10-24 10:40:15,420:INFO:Initializing Quadratic Discriminant Analysis
2023-10-24 10:40:15,421:INFO:Total runtime is 0.09312508106231687 minutes
2023-10-24 10:40:15,423:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:15,424:INFO:Initializing create_model()
2023-10-24 10:40:15,424:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:15,424:INFO:Checking exceptions
2023-10-24 10:40:15,424:INFO:Importing libraries
2023-10-24 10:40:15,424:INFO:Copying training dataset
2023-10-24 10:40:15,426:INFO:Defining folds
2023-10-24 10:40:15,426:INFO:Declaring metric variables
2023-10-24 10:40:15,428:INFO:Importing untrained model
2023-10-24 10:40:15,430:INFO:Quadratic Discriminant Analysis Imported successfully
2023-10-24 10:40:15,435:INFO:Starting cross validation
2023-10-24 10:40:15,436:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:15,496:INFO:Calculating mean and std
2023-10-24 10:40:15,497:INFO:Creating metrics dataframe
2023-10-24 10:40:15,499:INFO:Uploading results into container
2023-10-24 10:40:15,500:INFO:Uploading model into container now
2023-10-24 10:40:15,500:INFO:_master_model_container: 8
2023-10-24 10:40:15,500:INFO:_display_container: 2
2023-10-24 10:40:15,500:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-10-24 10:40:15,500:INFO:create_model() successfully completed......................................
2023-10-24 10:40:15,566:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:15,566:INFO:Creating metrics dataframe
2023-10-24 10:40:15,574:INFO:Initializing Ada Boost Classifier
2023-10-24 10:40:15,574:INFO:Total runtime is 0.0956775665283203 minutes
2023-10-24 10:40:15,576:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:15,576:INFO:Initializing create_model()
2023-10-24 10:40:15,576:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:15,576:INFO:Checking exceptions
2023-10-24 10:40:15,576:INFO:Importing libraries
2023-10-24 10:40:15,577:INFO:Copying training dataset
2023-10-24 10:40:15,579:INFO:Defining folds
2023-10-24 10:40:15,579:INFO:Declaring metric variables
2023-10-24 10:40:15,581:INFO:Importing untrained model
2023-10-24 10:40:15,583:INFO:Ada Boost Classifier Imported successfully
2023-10-24 10:40:15,587:INFO:Starting cross validation
2023-10-24 10:40:15,588:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:15,788:INFO:Calculating mean and std
2023-10-24 10:40:15,789:INFO:Creating metrics dataframe
2023-10-24 10:40:15,792:INFO:Uploading results into container
2023-10-24 10:40:15,792:INFO:Uploading model into container now
2023-10-24 10:40:15,793:INFO:_master_model_container: 9
2023-10-24 10:40:15,793:INFO:_display_container: 2
2023-10-24 10:40:15,793:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=123)
2023-10-24 10:40:15,793:INFO:create_model() successfully completed......................................
2023-10-24 10:40:15,866:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:15,866:INFO:Creating metrics dataframe
2023-10-24 10:40:15,875:INFO:Initializing Gradient Boosting Classifier
2023-10-24 10:40:15,875:INFO:Total runtime is 0.1006966988245646 minutes
2023-10-24 10:40:15,877:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:15,877:INFO:Initializing create_model()
2023-10-24 10:40:15,877:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:15,878:INFO:Checking exceptions
2023-10-24 10:40:15,878:INFO:Importing libraries
2023-10-24 10:40:15,878:INFO:Copying training dataset
2023-10-24 10:40:15,880:INFO:Defining folds
2023-10-24 10:40:15,880:INFO:Declaring metric variables
2023-10-24 10:40:15,882:INFO:Importing untrained model
2023-10-24 10:40:15,885:INFO:Gradient Boosting Classifier Imported successfully
2023-10-24 10:40:15,889:INFO:Starting cross validation
2023-10-24 10:40:15,890:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:16,188:INFO:Calculating mean and std
2023-10-24 10:40:16,189:INFO:Creating metrics dataframe
2023-10-24 10:40:16,192:INFO:Uploading results into container
2023-10-24 10:40:16,192:INFO:Uploading model into container now
2023-10-24 10:40:16,193:INFO:_master_model_container: 10
2023-10-24 10:40:16,193:INFO:_display_container: 2
2023-10-24 10:40:16,193:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-10-24 10:40:16,194:INFO:create_model() successfully completed......................................
2023-10-24 10:40:16,262:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:16,262:INFO:Creating metrics dataframe
2023-10-24 10:40:16,270:INFO:Initializing Linear Discriminant Analysis
2023-10-24 10:40:16,270:INFO:Total runtime is 0.10728394985198973 minutes
2023-10-24 10:40:16,272:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:16,272:INFO:Initializing create_model()
2023-10-24 10:40:16,272:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:16,272:INFO:Checking exceptions
2023-10-24 10:40:16,272:INFO:Importing libraries
2023-10-24 10:40:16,272:INFO:Copying training dataset
2023-10-24 10:40:16,275:INFO:Defining folds
2023-10-24 10:40:16,275:INFO:Declaring metric variables
2023-10-24 10:40:16,277:INFO:Importing untrained model
2023-10-24 10:40:16,279:INFO:Linear Discriminant Analysis Imported successfully
2023-10-24 10:40:16,282:INFO:Starting cross validation
2023-10-24 10:40:16,283:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:16,343:INFO:Calculating mean and std
2023-10-24 10:40:16,343:INFO:Creating metrics dataframe
2023-10-24 10:40:16,345:INFO:Uploading results into container
2023-10-24 10:40:16,346:INFO:Uploading model into container now
2023-10-24 10:40:16,346:INFO:_master_model_container: 11
2023-10-24 10:40:16,346:INFO:_display_container: 2
2023-10-24 10:40:16,347:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-10-24 10:40:16,347:INFO:create_model() successfully completed......................................
2023-10-24 10:40:16,411:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:16,411:INFO:Creating metrics dataframe
2023-10-24 10:40:16,419:INFO:Initializing Extra Trees Classifier
2023-10-24 10:40:16,419:INFO:Total runtime is 0.10976039965947468 minutes
2023-10-24 10:40:16,421:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:16,421:INFO:Initializing create_model()
2023-10-24 10:40:16,421:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:16,421:INFO:Checking exceptions
2023-10-24 10:40:16,421:INFO:Importing libraries
2023-10-24 10:40:16,421:INFO:Copying training dataset
2023-10-24 10:40:16,424:INFO:Defining folds
2023-10-24 10:40:16,424:INFO:Declaring metric variables
2023-10-24 10:40:16,426:INFO:Importing untrained model
2023-10-24 10:40:16,428:INFO:Extra Trees Classifier Imported successfully
2023-10-24 10:40:16,432:INFO:Starting cross validation
2023-10-24 10:40:16,432:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:17,003:INFO:Calculating mean and std
2023-10-24 10:40:17,004:INFO:Creating metrics dataframe
2023-10-24 10:40:17,007:INFO:Uploading results into container
2023-10-24 10:40:17,007:INFO:Uploading model into container now
2023-10-24 10:40:17,008:INFO:_master_model_container: 12
2023-10-24 10:40:17,008:INFO:_display_container: 2
2023-10-24 10:40:17,008:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)
2023-10-24 10:40:17,009:INFO:create_model() successfully completed......................................
2023-10-24 10:40:17,077:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:17,077:INFO:Creating metrics dataframe
2023-10-24 10:40:17,085:INFO:Initializing Light Gradient Boosting Machine
2023-10-24 10:40:17,085:INFO:Total runtime is 0.12086411317189533 minutes
2023-10-24 10:40:17,087:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:17,087:INFO:Initializing create_model()
2023-10-24 10:40:17,087:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:17,088:INFO:Checking exceptions
2023-10-24 10:40:17,088:INFO:Importing libraries
2023-10-24 10:40:17,088:INFO:Copying training dataset
2023-10-24 10:40:17,090:INFO:Defining folds
2023-10-24 10:40:17,090:INFO:Declaring metric variables
2023-10-24 10:40:17,092:INFO:Importing untrained model
2023-10-24 10:40:17,094:INFO:Light Gradient Boosting Machine Imported successfully
2023-10-24 10:40:17,098:INFO:Starting cross validation
2023-10-24 10:40:17,099:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:20,007:INFO:Calculating mean and std
2023-10-24 10:40:20,007:INFO:Creating metrics dataframe
2023-10-24 10:40:20,010:INFO:Uploading results into container
2023-10-24 10:40:20,010:INFO:Uploading model into container now
2023-10-24 10:40:20,010:INFO:_master_model_container: 13
2023-10-24 10:40:20,011:INFO:_display_container: 2
2023-10-24 10:40:20,011:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-10-24 10:40:20,011:INFO:create_model() successfully completed......................................
2023-10-24 10:40:20,075:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:20,075:INFO:Creating metrics dataframe
2023-10-24 10:40:20,083:INFO:Initializing Dummy Classifier
2023-10-24 10:40:20,083:INFO:Total runtime is 0.1708388010660807 minutes
2023-10-24 10:40:20,085:INFO:SubProcess create_model() called ==================================
2023-10-24 10:40:20,086:INFO:Initializing create_model()
2023-10-24 10:40:20,086:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x146c1f220>, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:20,086:INFO:Checking exceptions
2023-10-24 10:40:20,086:INFO:Importing libraries
2023-10-24 10:40:20,086:INFO:Copying training dataset
2023-10-24 10:40:20,088:INFO:Defining folds
2023-10-24 10:40:20,088:INFO:Declaring metric variables
2023-10-24 10:40:20,090:INFO:Importing untrained model
2023-10-24 10:40:20,092:INFO:Dummy Classifier Imported successfully
2023-10-24 10:40:20,096:INFO:Starting cross validation
2023-10-24 10:40:20,097:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-10-24 10:40:20,115:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,119:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,120:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,126:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,131:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,131:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,134:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,134:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,136:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,141:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:20,149:INFO:Calculating mean and std
2023-10-24 10:40:20,150:INFO:Creating metrics dataframe
2023-10-24 10:40:20,152:INFO:Uploading results into container
2023-10-24 10:40:20,152:INFO:Uploading model into container now
2023-10-24 10:40:20,153:INFO:_master_model_container: 14
2023-10-24 10:40:20,153:INFO:_display_container: 2
2023-10-24 10:40:20,153:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2023-10-24 10:40:20,153:INFO:create_model() successfully completed......................................
2023-10-24 10:40:20,218:INFO:SubProcess create_model() end ==================================
2023-10-24 10:40:20,218:INFO:Creating metrics dataframe
2023-10-24 10:40:20,231:INFO:Initializing create_model()
2023-10-24 10:40:20,232:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-10-24 10:40:20,232:INFO:Checking exceptions
2023-10-24 10:40:20,233:INFO:Importing libraries
2023-10-24 10:40:20,233:INFO:Copying training dataset
2023-10-24 10:40:20,235:INFO:Defining folds
2023-10-24 10:40:20,236:INFO:Declaring metric variables
2023-10-24 10:40:20,236:INFO:Importing untrained model
2023-10-24 10:40:20,236:INFO:Declaring custom model
2023-10-24 10:40:20,236:INFO:Random Forest Classifier Imported successfully
2023-10-24 10:40:20,237:INFO:Cross validation set to False
2023-10-24 10:40:20,237:INFO:Fitting Model
2023-10-24 10:40:20,370:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-10-24 10:40:20,370:INFO:create_model() successfully completed......................................
2023-10-24 10:40:20,451:INFO:_master_model_container: 14
2023-10-24 10:40:20,451:INFO:_display_container: 2
2023-10-24 10:40:20,451:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-10-24 10:40:20,451:INFO:compare_models() successfully completed......................................
2023-10-24 10:40:20,538:INFO:Initializing evaluate_model()
2023-10-24 10:40:20,538:INFO:evaluate_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False), fold=None, fit_kwargs=None, plot_kwargs=None, feature_name=None, groups=None)
2023-10-24 10:40:20,548:INFO:Initializing plot_model()
2023-10-24 10:40:20,548:INFO:plot_model(plot=pipeline, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), verbose=False, display=None, display_format=None, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False), feature_name=None, fit_kwargs={}, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, system=True)
2023-10-24 10:40:20,548:INFO:Checking exceptions
2023-10-24 10:40:20,563:INFO:Preloading libraries
2023-10-24 10:40:20,569:INFO:Copying training dataset
2023-10-24 10:40:20,569:INFO:Plot type: pipeline
2023-10-24 10:40:20,776:INFO:Visual Rendered Successfully
2023-10-24 10:40:20,915:INFO:plot_model() successfully completed......................................
2023-10-24 10:40:21,006:INFO:Initializing predict_model()
2023-10-24 10:40:21,007:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x15686b010>)
2023-10-24 10:40:21,007:INFO:Checking exceptions
2023-10-24 10:40:21,008:INFO:Preloading libraries
2023-10-24 10:40:21,011:INFO:Set up data.
2023-10-24 10:40:21,015:INFO:Set up index.
2023-10-24 10:40:21,060:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/utils/generic.py:586: UserWarning: Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/utils/generic.py", line 580, in _calculate_metric
    calculated_metric = score_func(y_test, target, sample_weight=weights, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 87, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 572, in roc_auc_score
    return _average_binary_score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 339, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/utils/generic.py", line 584, in _calculate_metric
    calculated_metric = score_func(y_test, target, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 87, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 572, in roc_auc_score
    return _average_binary_score(
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 339, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

  warnings.warn(traceback.format_exc())

2023-10-24 10:40:21,061:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-10-24 10:40:21,157:INFO:Initializing save_model()
2023-10-24 10:40:21,157:INFO:save_model(model=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False), model_name=titanic_model, prep_pipe_=Pipeline(memory=FastMemory(location=/var/folders/h8/ybzdwy6x03l4xpqzfc0k7kpr0000gn/T/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['pclass', 'sex', 'age', 'sibsp',
                                             'parch', 'fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2023-10-24 10:40:21,157:INFO:Adding model into prep_pipe
2023-10-24 10:40:21,210:INFO:titanic_model.pkl saved in current working directory
2023-10-24 10:40:21,213:INFO:Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['pclass', 'sex', 'age', 'sibsp',
                                             'parch', 'fare'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='sqrt',
                                        max_leaf_nodes=None, max_samples=None,
                                        min_impurity_decrease=0.0,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=100, n_jobs=-1,
                                        oob_score=False, random_state=123,
                                        verbose=0, warm_start=False))],
         verbose=False)
2023-10-24 10:40:21,213:INFO:save_model() successfully completed......................................
2023-10-24 10:40:21,307:INFO:Initializing plot_model()
2023-10-24 10:40:21,307:INFO:plot_model(plot=auc, fold=None, verbose=True, display=None, display_format=None, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False), feature_name=None, fit_kwargs=None, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, system=True)
2023-10-24 10:40:21,307:INFO:Checking exceptions
2023-10-24 10:40:21,325:INFO:Preloading libraries
2023-10-24 10:40:21,331:INFO:Copying training dataset
2023-10-24 10:40:21,331:INFO:Plot type: auc
2023-10-24 10:40:21,366:INFO:Fitting Model
2023-10-24 10:40:21,367:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

2023-10-24 10:40:21,367:INFO:Scoring test/hold-out set
2023-10-24 10:40:21,546:INFO:Visual Rendered Successfully
2023-10-24 10:40:21,613:INFO:plot_model() successfully completed......................................
2023-10-24 10:40:21,630:INFO:Initializing plot_model()
2023-10-24 10:40:21,630:INFO:plot_model(plot=confusion_matrix, fold=None, verbose=True, display=None, display_format=None, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False), feature_name=None, fit_kwargs=None, groups=None, label=False, plot_kwargs=None, save=False, scale=1, self=<pycaret.classification.oop.ClassificationExperiment object at 0x152f3ae90>, system=True)
2023-10-24 10:40:21,631:INFO:Checking exceptions
2023-10-24 10:40:21,651:INFO:Preloading libraries
2023-10-24 10:40:21,658:INFO:Copying training dataset
2023-10-24 10:40:21,658:INFO:Plot type: confusion_matrix
2023-10-24 10:40:21,691:INFO:Fitting Model
2023-10-24 10:40:21,691:WARNING:/Users/charlesnanakwakye/cloud_AI_Group4/venv/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

2023-10-24 10:40:21,692:INFO:Scoring test/hold-out set
2023-10-24 10:40:21,803:INFO:Visual Rendered Successfully
2023-10-24 10:40:21,870:INFO:plot_model() successfully completed......................................
